using System;
using UpdateControls;

namespace NanasNook.ViewModel.FrontOfficeScreen
{
	public class DeliveryDetailSnapshot
	{
		private string _city = string.Empty;
		private string _streetAddress = string.Empty;
		private DateTime _expectedDeliveryDate = DateTime.Now;
		private string _deliveryInstructions = string.Empty;

		#region Independent properties
		// Generated by Update Controls --------------------------------
		private Independent _indCity = new Independent();
		private Independent _indStreetAddress = new Independent();
		private Independent _indExpectedDeliveryDate = new Independent();
		private Independent _indDeliveryInstructions = new Independent();

		public string City
		{
			get { _indCity.OnGet(); return _city; }
			set { _indCity.OnSet(); _city = value; }
		}

		public string StreetAddress
		{
			get { _indStreetAddress.OnGet(); return _streetAddress; }
			set { _indStreetAddress.OnSet(); _streetAddress = value; }
		}

		public DateTime ExpectedDeliveryDate
		{
			get { _indExpectedDeliveryDate.OnGet(); return _expectedDeliveryDate; }
			set { _indExpectedDeliveryDate.OnSet(); _expectedDeliveryDate = value; }
		}

		public string DeliveryInstructions
		{
			get { _indDeliveryInstructions.OnGet(); return _deliveryInstructions; }
			set { _indDeliveryInstructions.OnSet(); _deliveryInstructions = value; }
		}
		// End generated code --------------------------------
		#endregion

		public void Reset()
		{
			City = string.Empty;
			StreetAddress = string.Empty;
			ExpectedDeliveryDate = DateTime.Now;
			DeliveryInstructions = string.Empty;
		}
	}
}
